name: UnikGuild
version: 1.0.0
main: me.smokietrue.unikguild.Main
api-version: '1.21'
authors: [smokietrue]
description: Плагин для управления гильдиями

commands:
  g:
    description: Основные команды гильдии
    usage: /g <accept|deny|info|kick|leave|disband|chat|role|assign>
  guilds:
    description: Административные команды гильдий
    usage: /guilds <list|delete|give>
    permission: unikguild.admin
  guildcolor:
    description: Выбор цвета для гильдии
    usage: /guildcolor <цвет>
    permission: unikguild.use

permissions:
  unikguild.admin:
    description: Административные права гильдий
    default: op
  unikguild.use:
    description: Использование основных функций гильдий
    default: true